name: DevSecOps Pipeline Demo

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  # 1️⃣ SonarQube Static Code Scan
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Sonar Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          organization: ${{ secrets.SONAR_ORG }}
          token: ${{ secrets.SONAR_TOKEN }}
          projectKey: my-cicd-app


  # 2️⃣ Snyk Vulnerability Scan (Code)
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Snyk Code Scan
        uses: snyk/actions/java@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  # 3️⃣ Trivy Source Code Scan (Filesystem)
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trivy File System Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'
