name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  # 1️⃣ Sonar Static Code Analysis
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=my-cicd-app
            -Dsonar.organization=praveenaprabaharan20
            -Dsonar.host.url=https://sonarcloud.io


  # 2️⃣ Snyk Code Vulnerability Scan
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Snyk Code Scan
        uses: snyk/actions@master
        with:
          args: code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  # 3️⃣ Trivy Source Code Scan
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trivy File System Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
